
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeNinjaFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:2 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Program used to build from build.ninja files."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "ninja-build"
      - "ninja"
      - "samu"
    candidate_directories:
      - "C:/Users/anhnhat/.codex/tmp/arg0/codex-arg00pt3E0/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Program Files (x86)/Citrix/HDX/bin/"
      - "C:/Program Files/Citrix/HDX/bin/"
      - "C:/Program Files/TortoiseSVN/bin/"
      - "C:/Program Files/nodejs/"
      - "C:/Program Files/Perforce/"
      - "C:/Program Files/CMake/bin/"
      - "C:/Program Files/dotnet/"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
      - "C:/Users/anhnhat/AppData/Local/Programs/Python/Python314/Scripts/"
      - "C:/Users/anhnhat/AppData/Local/Programs/Python/Python314/"
      - "C:/Users/anhnhat/AppData/Local/Programs/Python/Launcher/"
      - "C:/Users/anhnhat/AppData/Local/Microsoft/WindowsApps/"
      - "D:/dev/UNREAL_ENGINE/UE/UE_5.6/Engine/Binaries/Win64/"
      - "C:/Users/anhnhat/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "C:/Users/anhnhat/AppData/Roaming/npm/"
      - "C:/Users/anhnhat/.dotnet/tools/"
      - "C:/Users/anhnhat/AppData/Local/Programs/Git/cmd/"
      - "C:/Users/anhnhat/AppData/Local/Programs/Ollama/"
      - "C:/Users/anhnhat/.vscode/extensions/openai.chatgpt-0.4.73-win32-x64/bin/windows-x86_64/"
    searched_directories:
      - "C:/Users/anhnhat/.codex/tmp/arg0/codex-arg00pt3E0/ninja-build.com"
      - "C:/Users/anhnhat/.codex/tmp/arg0/codex-arg00pt3E0/ninja-build.exe"
      - "C:/Users/anhnhat/.codex/tmp/arg0/codex-arg00pt3E0/ninja-build"
      - "C:/Users/anhnhat/.codex/tmp/arg0/codex-arg00pt3E0/ninja.com"
      - "C:/Users/anhnhat/.codex/tmp/arg0/codex-arg00pt3E0/ninja.exe"
      - "C:/Users/anhnhat/.codex/tmp/arg0/codex-arg00pt3E0/ninja"
      - "C:/Users/anhnhat/.codex/tmp/arg0/codex-arg00pt3E0/samu.com"
      - "C:/Users/anhnhat/.codex/tmp/arg0/codex-arg00pt3E0/samu.exe"
      - "C:/Users/anhnhat/.codex/tmp/arg0/codex-arg00pt3E0/samu"
      - "C:/Windows/System32/ninja-build.com"
      - "C:/Windows/System32/ninja-build.exe"
      - "C:/Windows/System32/ninja-build"
      - "C:/Windows/System32/ninja.com"
      - "C:/Windows/System32/ninja.exe"
      - "C:/Windows/System32/ninja"
      - "C:/Windows/System32/samu.com"
      - "C:/Windows/System32/samu.exe"
      - "C:/Windows/System32/samu"
      - "C:/Windows/ninja-build.com"
      - "C:/Windows/ninja-build.exe"
      - "C:/Windows/ninja-build"
      - "C:/Windows/ninja.com"
      - "C:/Windows/ninja.exe"
      - "C:/Windows/ninja"
      - "C:/Windows/samu.com"
      - "C:/Windows/samu.exe"
      - "C:/Windows/samu"
      - "C:/Windows/System32/wbem/ninja-build.com"
      - "C:/Windows/System32/wbem/ninja-build.exe"
      - "C:/Windows/System32/wbem/ninja-build"
      - "C:/Windows/System32/wbem/ninja.com"
      - "C:/Windows/System32/wbem/ninja.exe"
      - "C:/Windows/System32/wbem/ninja"
      - "C:/Windows/System32/wbem/samu.com"
      - "C:/Windows/System32/wbem/samu.exe"
      - "C:/Windows/System32/wbem/samu"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu"
      - "C:/Windows/System32/OpenSSH/ninja-build.com"
      - "C:/Windows/System32/OpenSSH/ninja-build.exe"
      - "C:/Windows/System32/OpenSSH/ninja-build"
      - "C:/Windows/System32/OpenSSH/ninja.com"
      - "C:/Windows/System32/OpenSSH/ninja.exe"
      - "C:/Windows/System32/OpenSSH/ninja"
      - "C:/Windows/System32/OpenSSH/samu.com"
      - "C:/Windows/System32/OpenSSH/samu.exe"
      - "C:/Windows/System32/OpenSSH/samu"
      - "C:/Program Files (x86)/Citrix/HDX/bin/ninja-build.com"
      - "C:/Program Files (x86)/Citrix/HDX/bin/ninja-build.exe"
      - "C:/Program Files (x86)/Citrix/HDX/bin/ninja-build"
      - "C:/Program Files (x86)/Citrix/HDX/bin/ninja.com"
      - "C:/Program Files (x86)/Citrix/HDX/bin/ninja.exe"
      - "C:/Program Files (x86)/Citrix/HDX/bin/ninja"
      - "C:/Program Files (x86)/Citrix/HDX/bin/samu.com"
      - "C:/Program Files (x86)/Citrix/HDX/bin/samu.exe"
      - "C:/Program Files (x86)/Citrix/HDX/bin/samu"
      - "C:/Program Files/Citrix/HDX/bin/ninja-build.com"
      - "C:/Program Files/Citrix/HDX/bin/ninja-build.exe"
      - "C:/Program Files/Citrix/HDX/bin/ninja-build"
      - "C:/Program Files/Citrix/HDX/bin/ninja.com"
      - "C:/Program Files/Citrix/HDX/bin/ninja.exe"
      - "C:/Program Files/Citrix/HDX/bin/ninja"
      - "C:/Program Files/Citrix/HDX/bin/samu.com"
      - "C:/Program Files/Citrix/HDX/bin/samu.exe"
      - "C:/Program Files/Citrix/HDX/bin/samu"
      - "C:/Program Files/TortoiseSVN/bin/ninja-build.com"
      - "C:/Program Files/TortoiseSVN/bin/ninja-build.exe"
      - "C:/Program Files/TortoiseSVN/bin/ninja-build"
      - "C:/Program Files/TortoiseSVN/bin/ninja.com"
      - "C:/Program Files/TortoiseSVN/bin/ninja.exe"
      - "C:/Program Files/TortoiseSVN/bin/ninja"
      - "C:/Program Files/TortoiseSVN/bin/samu.com"
      - "C:/Program Files/TortoiseSVN/bin/samu.exe"
      - "C:/Program Files/TortoiseSVN/bin/samu"
      - "C:/Program Files/nodejs/ninja-build.com"
      - "C:/Program Files/nodejs/ninja-build.exe"
      - "C:/Program Files/nodejs/ninja-build"
      - "C:/Program Files/nodejs/ninja.com"
      - "C:/Program Files/nodejs/ninja.exe"
      - "C:/Program Files/nodejs/ninja"
      - "C:/Program Files/nodejs/samu.com"
      - "C:/Program Files/nodejs/samu.exe"
      - "C:/Program Files/nodejs/samu"
      - "C:/Program Files/Perforce/ninja-build.com"
      - "C:/Program Files/Perforce/ninja-build.exe"
      - "C:/Program Files/Perforce/ninja-build"
      - "C:/Program Files/Perforce/ninja.com"
      - "C:/Program Files/Perforce/ninja.exe"
      - "C:/Program Files/Perforce/ninja"
      - "C:/Program Files/Perforce/samu.com"
      - "C:/Program Files/Perforce/samu.exe"
      - "C:/Program Files/Perforce/samu"
      - "C:/Program Files/CMake/bin/ninja-build.com"
      - "C:/Program Files/CMake/bin/ninja-build.exe"
      - "C:/Program Files/CMake/bin/ninja-build"
      - "C:/Program Files/CMake/bin/ninja.com"
      - "C:/Program Files/CMake/bin/ninja.exe"
      - "C:/Program Files/CMake/bin/ninja"
      - "C:/Program Files/CMake/bin/samu.com"
      - "C:/Program Files/CMake/bin/samu.exe"
      - "C:/Program Files/CMake/bin/samu"
      - "C:/Program Files/dotnet/ninja-build.com"
      - "C:/Program Files/dotnet/ninja-build.exe"
      - "C:/Program Files/dotnet/ninja-build"
      - "C:/Program Files/dotnet/ninja.com"
      - "C:/Program Files/dotnet/ninja.exe"
      - "C:/Program Files/dotnet/ninja"
      - "C:/Program Files/dotnet/samu.com"
      - "C:/Program Files/dotnet/samu.exe"
      - "C:/Program Files/dotnet/samu"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja-build.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja-build.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja-build"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/samu.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/samu.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/samu"
      - "C:/Users/anhnhat/AppData/Local/Programs/Python/Python314/Scripts/ninja-build.com"
      - "C:/Users/anhnhat/AppData/Local/Programs/Python/Python314/Scripts/ninja-build.exe"
      - "C:/Users/anhnhat/AppData/Local/Programs/Python/Python314/Scripts/ninja-build"
      - "C:/Users/anhnhat/AppData/Local/Programs/Python/Python314/Scripts/ninja.com"
      - "C:/Users/anhnhat/AppData/Local/Programs/Python/Python314/Scripts/ninja.exe"
      - "C:/Users/anhnhat/AppData/Local/Programs/Python/Python314/Scripts/ninja"
      - "C:/Users/anhnhat/AppData/Local/Programs/Python/Python314/Scripts/samu.com"
      - "C:/Users/anhnhat/AppData/Local/Programs/Python/Python314/Scripts/samu.exe"
      - "C:/Users/anhnhat/AppData/Local/Programs/Python/Python314/Scripts/samu"
      - "C:/Users/anhnhat/AppData/Local/Programs/Python/Python314/ninja-build.com"
      - "C:/Users/anhnhat/AppData/Local/Programs/Python/Python314/ninja-build.exe"
      - "C:/Users/anhnhat/AppData/Local/Programs/Python/Python314/ninja-build"
      - "C:/Users/anhnhat/AppData/Local/Programs/Python/Python314/ninja.com"
      - "C:/Users/anhnhat/AppData/Local/Programs/Python/Python314/ninja.exe"
      - "C:/Users/anhnhat/AppData/Local/Programs/Python/Python314/ninja"
      - "C:/Users/anhnhat/AppData/Local/Programs/Python/Python314/samu.com"
      - "C:/Users/anhnhat/AppData/Local/Programs/Python/Python314/samu.exe"
      - "C:/Users/anhnhat/AppData/Local/Programs/Python/Python314/samu"
      - "C:/Users/anhnhat/AppData/Local/Programs/Python/Launcher/ninja-build.com"
      - "C:/Users/anhnhat/AppData/Local/Programs/Python/Launcher/ninja-build.exe"
      - "C:/Users/anhnhat/AppData/Local/Programs/Python/Launcher/ninja-build"
      - "C:/Users/anhnhat/AppData/Local/Programs/Python/Launcher/ninja.com"
      - "C:/Users/anhnhat/AppData/Local/Programs/Python/Launcher/ninja.exe"
      - "C:/Users/anhnhat/AppData/Local/Programs/Python/Launcher/ninja"
      - "C:/Users/anhnhat/AppData/Local/Programs/Python/Launcher/samu.com"
      - "C:/Users/anhnhat/AppData/Local/Programs/Python/Launcher/samu.exe"
      - "C:/Users/anhnhat/AppData/Local/Programs/Python/Launcher/samu"
      - "C:/Users/anhnhat/AppData/Local/Microsoft/WindowsApps/ninja-build.com"
      - "C:/Users/anhnhat/AppData/Local/Microsoft/WindowsApps/ninja-build.exe"
      - "C:/Users/anhnhat/AppData/Local/Microsoft/WindowsApps/ninja-build"
      - "C:/Users/anhnhat/AppData/Local/Microsoft/WindowsApps/ninja.com"
      - "C:/Users/anhnhat/AppData/Local/Microsoft/WindowsApps/ninja.exe"
      - "C:/Users/anhnhat/AppData/Local/Microsoft/WindowsApps/ninja"
      - "C:/Users/anhnhat/AppData/Local/Microsoft/WindowsApps/samu.com"
      - "C:/Users/anhnhat/AppData/Local/Microsoft/WindowsApps/samu.exe"
      - "C:/Users/anhnhat/AppData/Local/Microsoft/WindowsApps/samu"
      - "D:/dev/UNREAL_ENGINE/UE/UE_5.6/Engine/Binaries/Win64/ninja-build.com"
      - "D:/dev/UNREAL_ENGINE/UE/UE_5.6/Engine/Binaries/Win64/ninja-build.exe"
      - "D:/dev/UNREAL_ENGINE/UE/UE_5.6/Engine/Binaries/Win64/ninja-build"
      - "D:/dev/UNREAL_ENGINE/UE/UE_5.6/Engine/Binaries/Win64/ninja.com"
      - "D:/dev/UNREAL_ENGINE/UE/UE_5.6/Engine/Binaries/Win64/ninja.exe"
      - "D:/dev/UNREAL_ENGINE/UE/UE_5.6/Engine/Binaries/Win64/ninja"
      - "D:/dev/UNREAL_ENGINE/UE/UE_5.6/Engine/Binaries/Win64/samu.com"
      - "D:/dev/UNREAL_ENGINE/UE/UE_5.6/Engine/Binaries/Win64/samu.exe"
      - "D:/dev/UNREAL_ENGINE/UE/UE_5.6/Engine/Binaries/Win64/samu"
      - "C:/Users/anhnhat/AppData/Local/Programs/Microsoft VS Code/bin/ninja-build.com"
      - "C:/Users/anhnhat/AppData/Local/Programs/Microsoft VS Code/bin/ninja-build.exe"
      - "C:/Users/anhnhat/AppData/Local/Programs/Microsoft VS Code/bin/ninja-build"
      - "C:/Users/anhnhat/AppData/Local/Programs/Microsoft VS Code/bin/ninja.com"
      - "C:/Users/anhnhat/AppData/Local/Programs/Microsoft VS Code/bin/ninja.exe"
      - "C:/Users/anhnhat/AppData/Local/Programs/Microsoft VS Code/bin/ninja"
      - "C:/Users/anhnhat/AppData/Local/Programs/Microsoft VS Code/bin/samu.com"
      - "C:/Users/anhnhat/AppData/Local/Programs/Microsoft VS Code/bin/samu.exe"
      - "C:/Users/anhnhat/AppData/Local/Programs/Microsoft VS Code/bin/samu"
      - "C:/Users/anhnhat/AppData/Roaming/npm/ninja-build.com"
      - "C:/Users/anhnhat/AppData/Roaming/npm/ninja-build.exe"
      - "C:/Users/anhnhat/AppData/Roaming/npm/ninja-build"
      - "C:/Users/anhnhat/AppData/Roaming/npm/ninja.com"
      - "C:/Users/anhnhat/AppData/Roaming/npm/ninja.exe"
      - "C:/Users/anhnhat/AppData/Roaming/npm/ninja"
      - "C:/Users/anhnhat/AppData/Roaming/npm/samu.com"
      - "C:/Users/anhnhat/AppData/Roaming/npm/samu.exe"
      - "C:/Users/anhnhat/AppData/Roaming/npm/samu"
      - "C:/Users/anhnhat/.dotnet/tools/ninja-build.com"
      - "C:/Users/anhnhat/.dotnet/tools/ninja-build.exe"
      - "C:/Users/anhnhat/.dotnet/tools/ninja-build"
      - "C:/Users/anhnhat/.dotnet/tools/ninja.com"
      - "C:/Users/anhnhat/.dotnet/tools/ninja.exe"
      - "C:/Users/anhnhat/.dotnet/tools/ninja"
      - "C:/Users/anhnhat/.dotnet/tools/samu.com"
      - "C:/Users/anhnhat/.dotnet/tools/samu.exe"
      - "C:/Users/anhnhat/.dotnet/tools/samu"
      - "C:/Users/anhnhat/AppData/Local/Programs/Git/cmd/ninja-build.com"
      - "C:/Users/anhnhat/AppData/Local/Programs/Git/cmd/ninja-build.exe"
      - "C:/Users/anhnhat/AppData/Local/Programs/Git/cmd/ninja-build"
      - "C:/Users/anhnhat/AppData/Local/Programs/Git/cmd/ninja.com"
      - "C:/Users/anhnhat/AppData/Local/Programs/Git/cmd/ninja.exe"
      - "C:/Users/anhnhat/AppData/Local/Programs/Git/cmd/ninja"
      - "C:/Users/anhnhat/AppData/Local/Programs/Git/cmd/samu.com"
      - "C:/Users/anhnhat/AppData/Local/Programs/Git/cmd/samu.exe"
      - "C:/Users/anhnhat/AppData/Local/Programs/Git/cmd/samu"
      - "C:/Users/anhnhat/AppData/Local/Programs/Ollama/ninja-build.com"
      - "C:/Users/anhnhat/AppData/Local/Programs/Ollama/ninja-build.exe"
      - "C:/Users/anhnhat/AppData/Local/Programs/Ollama/ninja-build"
      - "C:/Users/anhnhat/AppData/Local/Programs/Ollama/ninja.com"
      - "C:/Users/anhnhat/AppData/Local/Programs/Ollama/ninja.exe"
      - "C:/Users/anhnhat/AppData/Local/Programs/Ollama/ninja"
      - "C:/Users/anhnhat/AppData/Local/Programs/Ollama/samu.com"
      - "C:/Users/anhnhat/AppData/Local/Programs/Ollama/samu.exe"
      - "C:/Users/anhnhat/AppData/Local/Programs/Ollama/samu"
      - "C:/Users/anhnhat/.vscode/extensions/openai.chatgpt-0.4.73-win32-x64/bin/windows-x86_64/ninja-build.com"
      - "C:/Users/anhnhat/.vscode/extensions/openai.chatgpt-0.4.73-win32-x64/bin/windows-x86_64/ninja-build.exe"
      - "C:/Users/anhnhat/.vscode/extensions/openai.chatgpt-0.4.73-win32-x64/bin/windows-x86_64/ninja-build"
      - "C:/Users/anhnhat/.vscode/extensions/openai.chatgpt-0.4.73-win32-x64/bin/windows-x86_64/ninja.com"
      - "C:/Users/anhnhat/.vscode/extensions/openai.chatgpt-0.4.73-win32-x64/bin/windows-x86_64/ninja.exe"
      - "C:/Users/anhnhat/.vscode/extensions/openai.chatgpt-0.4.73-win32-x64/bin/windows-x86_64/ninja"
      - "C:/Users/anhnhat/.vscode/extensions/openai.chatgpt-0.4.73-win32-x64/bin/windows-x86_64/samu.com"
      - "C:/Users/anhnhat/.vscode/extensions/openai.chatgpt-0.4.73-win32-x64/bin/windows-x86_64/samu.exe"
      - "C:/Users/anhnhat/.vscode/extensions/openai.chatgpt-0.4.73-win32-x64/bin/windows-x86_64/samu"
    found: false
    search_context:
      ENV{PATH}:
        - "C:\\Users\\anhnhat\\.codex\\tmp\\arg0\\codex-arg00pt3E0"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files (x86)\\Citrix\\HDX\\bin\\"
        - "C:\\Program Files\\Citrix\\HDX\\bin\\"
        - "C:\\Program Files\\TortoiseSVN\\bin"
        - "C:\\Program Files\\nodejs\\"
        - "C:\\Program Files\\Perforce\\"
        - "C:\\Program Files\\CMake\\bin"
        - "C:\\Program Files\\dotnet\\"
        - "C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\"
        - "C:\\Users\\anhnhat\\AppData\\Local\\Programs\\Python\\Python314\\Scripts\\"
        - "C:\\Users\\anhnhat\\AppData\\Local\\Programs\\Python\\Python314\\"
        - "C:\\Users\\anhnhat\\AppData\\Local\\Programs\\Python\\Launcher\\"
        - "C:\\Users\\anhnhat\\AppData\\Local\\Microsoft\\WindowsApps"
        - "D:\\dev\\UNREAL_ENGINE\\UE\\UE_5.6\\Engine\\Binaries\\Win64"
        - "C:\\Users\\anhnhat\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\Users\\anhnhat\\AppData\\Roaming\\npm"
        - "C:\\Users\\anhnhat\\.dotnet\\tools"
        - "C:\\Users\\anhnhat\\AppData\\Local\\Programs\\Git\\cmd"
        - "C:\\Users\\anhnhat\\AppData\\Local\\Programs\\Ollama"
        - "c:\\Users\\anhnhat\\.vscode\\extensions\\openai.chatgpt-0.4.73-win32-x64\\bin\\windows-x86_64"
...
